# run: conda env create --file environment.yml
name: wildhunt
channels:
- conda-forge
- defaults
dependencies:
- python>=3.8.5
- dask
- pyarrow
- astropy>=4.0.2
- matplotlib>=3.3.1
- numpy>=1.19.1
- pandas>=1.1.3
- pip>=20.3.3
- scipy>=1.5.0
- pytables>=3.6.1
- pyyaml >= 5.4.1
- h5py
- sphinx>=1.4
- ipykernel
- pip:
  - nbsphinx
  - nbsphinx-link

