
ls_dr9_default_columns = """
      match.objid,
      match.ls_id,
      match.ra,
      match.dec,
      match.flux_g, match.flux_ivar_g,
      match.flux_r, match.flux_ivar_r,
      match.flux_z, match.flux_ivar_z,
      match.flux_w1, match.flux_ivar_w1,
      match.flux_w2, match.flux_ivar_w2,
      match.flux_w4, match.flux_ivar_w3,
      match.flux_w3, match.flux_ivar_w4,
      match.mag_g,
      match.mag_r,
      match.mag_z,
      match.mag_w1,
      match.mag_w2,
      match.mag_w3,
      match.mag_w4,
      match.maskbits,
      match.snr_g,
      match.snr_r,
      match.snr_z,
      match.snr_w1,
      match.snr_w2,
      match.snr_w3,
      match.snr_w4,
      match.wisemask_w1,
      match.wisemask_w2,
      match.type, 
      match.ebv, 
  """