df_path: ./data/Euclid_dr1_north_sources.csv
ra: right_ascension
dec: declination
fov: 4
cutout_path: /data/group-schindler/ts/data/Euclid/cutout/dr1_north/  # change cutout_path to the path you located
surveys: [Euclid, Euclid, Euclid, Euclid, Euclid]
bands: [I, Z, Y, J, H]
visual_classes:
  Artifact: [edge, diffraction spike, hot pixel, masked, other]
  Affects photometry:
    options: ["yes", "no"]
    exclusive: true
  Photometry:
    options: [single, offset single, companions, offset multiple, extended]
    exclusive: true
    default: single
  Compactness:
    options: ["yes", "no"]
    exclusive: true
    default: "yes"
  VIS detection:
    options: [no vis, weak vis, strong vis]
    exclusive: true
    default: no vis
verbosity: 2
euclid: true
saved_csv: Euclid_checked_dr1_north.csv
rgb_bands: [H, J, Y]
rgb_survey: Euclid
